import manifest from "@/public/assets/bellbit/hero/manifest.json";

type HeroManifest = typeof manifest & {
  frameExtension?: string;
  mobileFrameExtension?: string;
  posterExtension?: string;
};

const m = manifest as HeroManifest;
const desktopExt = m.frameExtension ?? "jpg";
const mobileExt = m.mobileFrameExtension ?? "jpg";
const posterExt = m.posterExtension ?? "jpg";

/**
 * Everything about the hero frame sequence lives here so nothing else in the
 * codebase hardcodes a frame count, path, or dimension. Values come straight
 * from manifest.json, generated by scripts/process-hero-frames.mjs from the
 * Bell bit hero frames/ source folder.
 */
export const heroSequence = {
  frameCount: m.frameCount,
  frameWidth: m.frameWidth,
  frameHeight: m.frameHeight,
  framePath: (index: number) =>
    `/assets/bellbit/hero/frames/frame-${String(index + 1).padStart(m.padWidth, "0")}.${desktopExt}`,

  mobile: {
    frameCount: m.mobileFrameCount,
    frameWidth: m.mobileFrameWidth,
    frameHeight: m.mobileFrameHeight,
    framePath: (index: number) =>
      `/assets/bellbit/hero/frames-mobile/frame-${String(index + 1).padStart(
        m.mobilePadWidth,
        "0"
      )}.${mobileExt}`,
  },

  posterPath: `/assets/bellbit/hero/poster.${posterExt}`,
} as const;

/** ~0.72vh of scroll per desktop frame — enough room for copy to breathe. */
const VH_PER_FRAME = 0.72;

/** How many frames to prefetch before scroll on fast vs slow networks. */
export function heroInitialWindow(profile: "fast" | "slow" | "unknown") {
  const base = Math.min(24, Math.max(12, Math.ceil(m.frameCount * 0.05)));
  if (profile === "slow") return Math.min(8, base);
  if (profile === "unknown") return Math.min(12, base);
  return base;
}

/** Max parallel frame requests — keeps slow links from stalling frame 0. */
export function heroLoadConcurrency(profile: "fast" | "slow" | "unknown") {
  if (profile === "slow") return 2;
  if (profile === "unknown") return 3;
  return 6;
}

export const heroBehavior = {
  /** Scroll distance mapped to the full frame sequence, in viewport heights. */
  pinDistanceVh: Math.round(m.frameCount * VH_PER_FRAME),
  /** Default eager preload window (fast networks). Prefer heroInitialWindow() at runtime. */
  initialWindow: Math.min(24, Math.max(12, Math.ceil(m.frameCount * 0.05))),
  /** Max decoded frames in memory — wide enough to avoid re-fetch while scrubbing. */
  cacheWindow: Math.min(160, Math.max(96, Math.ceil(m.frameCount * 0.4))),
  /**
   * ScrollTrigger scrub lag (seconds). A small amount of smoothing keeps the
   * canvas in sync with Lenis without feeling jittery on fast wheel input.
   */
  scrubSmoothing: 0.55,
  /**
   * Scroll choreography (0–1 = full frame sequence).
   * Primary exits early; secondary lines stagger across the mid/late scrub.
   */
  primaryHoldEnd: 0.07,
  primaryFadeEnd: 0.2,
  /** Equal windows from primary exit → hero end; last line fades only at the final scroll. */
  secondaryLineWindows: [
    { start: 0.2, end: 0.44 },
    { start: 0.48, end: 0.72 },
    { start: 0.76, end: 1 },
  ] as const,
  secondaryLineFade: 0.055,
  /** Last line exit — kept short so remaining frames are used as visible hold time. */
  secondaryLineLastExitFade: 0.035,
} as const;

export type HeroLineWindow = (typeof heroBehavior.secondaryLineWindows)[number];

/** Primary hero copy: brief hold, then fade before secondary lines begin. */
export function heroPrimaryOpacity(progress: number): number {
  const { primaryHoldEnd, primaryFadeEnd } = heroBehavior;
  if (progress <= primaryHoldEnd) return 1;
  if (progress >= primaryFadeEnd) return 0;
  const t = (progress - primaryHoldEnd) / (primaryFadeEnd - primaryHoldEnd);
  return 1 - t;
}

/** Secondary line: ease in at window start, hold, ease out at window end (mirrors entrance motion). */
export function heroLineOpacity(
  progress: number,
  window: HeroLineWindow,
  options?: { isLast?: boolean },
): number {
  const fadeIn = heroBehavior.secondaryLineFade;
  const fadeOut =
    options?.isLast && window.end === 1
      ? heroBehavior.secondaryLineLastExitFade
      : fadeIn;
  const { start, end } = window;

  if (progress <= start) return 0;
  if (progress > end) return 0;

  const fadeInEnd = start + fadeIn;
  const fadeOutStart = end - fadeOut;

  if (progress < fadeInEnd) {
    const t = (progress - start) / fadeIn;
    return 1 - (1 - t) ** 3;
  }

  if (progress > fadeOutStart) {
    const t = (progress - fadeOutStart) / fadeOut;
    return (1 - t) ** 3;
  }

  return 1;
}
