import manifest from "@/public/assets/bellbit/hero/manifest.json";

type HeroManifest = typeof manifest & {
  frameExtension?: string;
  mobileFrameExtension?: string;
  posterExtension?: string;
};

const m = manifest as HeroManifest;
const desktopExt = m.frameExtension ?? "jpg";
const mobileExt = m.mobileFrameExtension ?? "jpg";
const posterExt = m.posterExtension ?? "jpg";

/**
 * Everything about the hero frame sequence lives here so nothing else in the
 * codebase hardcodes a frame count, path, or dimension. Values come straight
 * from manifest.json, generated by scripts/process-hero-frames.mjs from the
 * Bell bit hero frames/ source folder.
 */
export const heroSequence = {
  frameCount: m.frameCount,
  frameWidth: m.frameWidth,
  frameHeight: m.frameHeight,
  framePath: (index: number) =>
    `/assets/bellbit/hero/frames/frame-${String(index + 1).padStart(m.padWidth, "0")}.${desktopExt}`,

  mobile: {
    frameCount: m.mobileFrameCount,
    frameWidth: m.mobileFrameWidth,
    frameHeight: m.mobileFrameHeight,
    framePath: (index: number) =>
      `/assets/bellbit/hero/frames-mobile/frame-${String(index + 1).padStart(
        m.mobilePadWidth,
        "0"
      )}.${mobileExt}`,
  },

  posterPath: `/assets/bellbit/hero/poster.${posterExt}`,
} as const;

/** ~0.72vh of scroll per desktop frame — enough room for copy to breathe. */
const VH_PER_FRAME = 0.72;

export const heroBehavior = {
  /** Scroll distance mapped to the full frame sequence, in viewport heights. */
  pinDistanceVh: Math.round(m.frameCount * VH_PER_FRAME),
  /** Frames to eagerly preload around frame 0 before the rest load progressively. */
  initialWindow: Math.min(24, Math.max(12, Math.ceil(m.frameCount * 0.05))),
  /** Max decoded frames in memory — wide enough to avoid re-fetch while scrubbing. */
  cacheWindow: Math.min(160, Math.max(96, Math.ceil(m.frameCount * 0.4))),
  /**
   * ScrollTrigger scrub lag (seconds). A small amount of smoothing keeps the
   * canvas in sync with Lenis without feeling jittery on fast wheel input.
   */
  scrubSmoothing: 0.55,
  /**
   * Scroll choreography (0–1 = full frame sequence).
   * Primary exits early; secondary lines stagger across the mid/late scrub.
   */
  primaryHoldEnd: 0.07,
  primaryFadeEnd: 0.2,
  secondaryLineStarts: [0.24, 0.38, 0.52, 0.66] as const,
  secondaryCtaStart: 0.8,
  secondaryLineFade: 0.08,
} as const;

/** Primary hero copy: brief hold, then fade before secondary lines begin. */
export function heroPrimaryOpacity(progress: number): number {
  const { primaryHoldEnd, primaryFadeEnd } = heroBehavior;
  if (progress <= primaryHoldEnd) return 1;
  if (progress >= primaryFadeEnd) return 0;
  const t = (progress - primaryHoldEnd) / (primaryFadeEnd - primaryHoldEnd);
  return 1 - t;
}

/** Secondary line reveal with ease-out so each beat lands gently. */
export function heroLineReveal(progress: number, start: number): number {
  const fade = heroBehavior.secondaryLineFade;
  if (progress <= start) return 0;
  const t = Math.min(1, (progress - start) / fade);
  return 1 - (1 - t) ** 3;
}
